In [18]:
import pandas as pd
df=pd.read_excel('file/score.xlsx',index_col='지원번호')

In [3]:
#문자열 함수
# df[df['이름'].str.startswith('강')]
df.loc[df['이름'].str.startswith('강')]

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  구로고  197  90  85  100  95  85      Python
2번    강태원  구로고  184  40  35   50  55  25        Java
3번    강호림  구로고  168  80  75   70  80  75  Javascript

In [ ]:
df.pd.read_excel('')
df.loc[df['이름'].str.con('강')]

In [16]:
#contains 포함 되어 있는 글자(~:not)

#lower, upper, capitalize
df['SW특기'].str.lower()
df['SW특기'].str.upper()
df['SW특기'].str.capitalize()

#isin: 여러개 검색['','']
langs=['python','java']
df[df['SW특기'].str.lower().isin(langs)]

#
# df[df['SW특기'].str.lower().isin(langs)]
df['SW특기']
df['SW특기'].str.contains('java',na=False)

번호
1      False
2      False
3      False
4      False
5      False
       ...
96     False
97     False
98     False
99     False
100    False
Name: SW특기, Length: 100, dtype: bool

In [28]:
df=pd.read_excel('file/students.xlsx',index_col='번호')
#s가 있는 이름을 모두 출력 (대문자 소문자 모두)
# df.[df['이름'].str.lower().str.contains('e')]
# df['학교'].str.replace('고','고등학교')

In [34]:
df=pd.read_excel('file/students.xlsx',index_col='번호')

#SW특기에서 java,c 출력
langs=['java','c']
df[df['SW특기'].str.lower().isin(langs)]['SW특기']

#java가 포한괴어 있는 글자를 모두 출력
df[df['SW특기'].str.lower().str.contains('java')]

             이름    학교  학년    키  국어  영어  수학        SW특기
번호
13       Ardene  디지털고   2  161  91  97  33        JAVA
14      Sibylle   구로고   1  197  82  81  38        JAVA
17        Alric   구로고   1  193  68  96  76        JAVA
18        Mozes   신림고   1  176  61  44  51        JAVA
20       Emelia   신림고   1  199  85  27  31  Javascript
30       Urbain  디지털고   3  197  83  72  36  Javascript
32       Hamnet   신림고   3  171  95  55  65  Javascript
36      Ainslee  디지털고   2  201  66  15  89  Javascript
41         Lyle  디지털고   3  164  55  47  73  Javascript
46          Nat  디지털고   2  171  70  38  82  Javascript
54          Ula   신림고   3  168  80  59  85        java
55     Emmanuel   구로고   2  191  63  27  83        JAVA
56        Valle   신림고   3  167  68  83  52        java
60      Malynda  디지털고   1  178  57  79  72        java
65         Kiri   신림고   3  178  64  83  68        JAVA
66       Joanie   신림고   1  200  75  24  85        java
68        Tresa   구로고   2  166  58  37  70        java
73        Moise  디지털고   3  185  90  83  65        JAVA
74        Lewes  디지털고   2  187  61  22  43        JAVA
76       Dionis  디지털고   1  192  58  40  63  Javascript
79       Vannie  디지털고   1  184  95  27  64  Javascript
82       Jamill   구로고   2  182  98   8  60        java
84          Ola  디지털고   3  170  84  77  77  Javascript
89       Norris  디지털고   3  174  68   9  51        java
91       Marika   신림고   2  189  89  22  32  Javascript
94         Kaja   신림고   1  202  53  44  78        java
95   Clementine   신림고   1  194  71  13  81        JAVA
100    Jonathan  디지털고   2  195  84  63  80        JAVA

In [ ]:
df=pd.read_excel('file/students.xlsx',index_col='번호')
df.loc[df['이름'].str.startswith('E)]

SyntaxError: unterminated string literal (detected at line 2) (2946411.py, line 2)